# Generated by Django 2.0.2 on 2018-02-20 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20180219_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='parent_resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='parent_resume',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resume.resume'),
        ),
    ]
